### ISSUE TITLE
Review website responsiveness

### ISSUE THREAD

**Issue by andreyluiz** [KenshiTech/www#17]
The responsiveness is kinda working, but it fails in some scenarios. We need to review it and fix what's not working.

**Comment by klidifia** [comment]
I'm not sure if this could be the cause of some of the issues but I note that the main menu doesn't convert to the mobile mode based on the viewport width, must be user agent or something - so reducing width in a desktop browser doesn't change to mobile, e.g.

![image](https://user-images.githubusercontent.com/1428056/157942551-12e1d817-81ab-48c1-944d-25a9236e4f05.png)
