### ISSUE TITLE
Migrate Kenshi tools page

### ISSUE THREAD

**Issue by andreyluiz** [KenshiTech/www#19]
One of the most important pages on the website is not yet migrated to the new website. Refer to https://old.kenshi.io/tools to know what to migrate. We should prioritize functionality over good design. But the website design guidelines must be followed.

**Comment by klidifia** [comment]
Any progress? N.B. There is a 404 -- https://docs.kenshi.io/guides/sell.html

**Comment by klidifia** [comment]
Feedback on new page has been positive https://kenshi.io/tools
